### ISSUE TITLE
Cannot use conditional coloring

### ISSUE THREAD

**Issue by krillin666** [open-nomie/nomie6-oss#80]
Hi @RdeLange , thanks for maintaining this amazing app.

I've been trying to use conditional coloring in widgets for about a month but it never works.

I set **green** for *under* and **red** for *above* a certain value. The problem is that the color is always **green** for any value I set, and independently of the value of the tracker. I also notice that the only way to make the color red, is to use a conditional coloring value that is negative (any negative number).
The last thing to add is that If I click on the *plus* sign, I get this dialog which doesn't do anything:
![image](https://github.com/open-nomie/nomie6-oss/assets/60305303/8302e4ba-c227-4e10-97ad-a839652170e3)

**Comment by RdeLange** [comment]
Hi,

thanks for reaching out. I see what you mean and it seems to be a bug indeed. I will have a look if I can fix it the coming weeks.

Regards,
Ronald

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: krillin666 ***@***.***>
Sent: Sunday, April 14, 2024 8:56:21 PM
To: open-nomie/nomie6-oss ***@***.***>
Cc: Ronald de Lange ***@***.***>; Mention ***@***.***>
Subject: [open-nomie/nomie6-oss] Cannot use conditional coloring (Issue #80)


Hi @RdeLange<https://github.com/RdeLange> , thanks for maintaining this amazing app.

I've been trying to use conditional coloring in widgets for about a month but it never works.

I set green for under and red for above a certain value. The problem is that the color is always green for any value I set, and independently of the value of the tracker. I also notice that the only way to make the color red, is to use a conditional coloring value that is negative (any negative number).
The last thing to add is that If I click on the plus sign, I get this dialog which doesn't do anything:
image.png (view on web)<https://github.com/open-nomie/nomie6-oss/assets/60305303/8302e4ba-c227-4e10-97ad-a839652170e3>

**Comment by RdeLange** [comment]
Hi,

I have fixed this bug and pushed it to production.
So it should work now, let me know if you have any further questions.

Regards,
Ronald

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: krillin666 ***@***.***>
Sent: Sunday, April 14, 2024 8:56:21 PM
To: open-nomie/nomie6-oss ***@***.***>
Cc: Ronald de Lange ***@***.***>; Mention ***@***.***>
Subject: [open-nomie/nomie6-oss] Cannot use conditional coloring (Issue #80)


Hi @RdeLange<https://github.com/RdeLange> , thanks for maintaining this amazing app.

I've been trying to use conditional coloring in widgets for about a month but it never works.

I set green for under and red for above a certain value. The problem is that the color is always green for any value I set, and independently of the value of the tracker. I also notice that the only way to make the color red, is to use a conditional coloring value that is negative (any negative number).
The last thing to add is that If I click on the plus sign, I get this dialog which doesn't do anything:
image.png (view on web)<https://github.com/open-nomie/nomie6-oss/assets/60305303/8302e4ba-c227-4e10-97ad-a839652170e3>

**Comment by krillin666** [comment]
Thanks ! It's working wonders !
